export type Category = "ALL" | "SCENE" | "MODEL" | "MOCKUP" | "GOBO" | "ADDON" | "GEO NODE"

export interface CategoryMeta {
  label: string
  total: number
}

export const categoryMeta: Record<Category, CategoryMeta> = {
  ALL:        { label: "All Assets",    total: 147 },
  SCENE:      { label: "Scenes",        total: 7   },
  MODEL:      { label: "3D Models",     total: 51  },
  MOCKUP:     { label: "Mockups",       total: 30  },
  GOBO:       { label: "Gobo Textures", total: 50  },
  ADDON:      { label: "Add-ons",       total: 4   },
  "GEO NODE": { label: "Geo Nodes",     total: 5   },
}

export const categoryOrder: Category[] = ["ALL", "SCENE", "MODEL", "MOCKUP", "GOBO", "ADDON", "GEO NODE"]

export interface Asset {
  id: number
  name: string
  slug: string
  category: Exclude<Category, "ALL">
  formats: string[]
  free: boolean
  isNew: boolean
  description: string
  meta: string
  disclaimer?: string
  whatYouGet?: string[]
  image_url?: string | null
  lemonsqueezy_url?: string | null
  required_plan_uid?: string | null
}

export const formatColor: Record<string, string> = {
  ".blend": "bg-orange-500/10 text-orange-500/80 border-orange-500/20",
  ".fbx":   "bg-blue-500/10 text-blue-500/80 border-blue-500/20",
  ".obj":   "bg-purple-500/10 text-purple-500/80 border-purple-500/20",
  ".exr":   "bg-cyan-500/10 text-cyan-500/80 border-cyan-500/20",
  ".png":   "bg-green-500/10 text-green-500/80 border-green-500/20",
  ".py":    "bg-yellow-500/10 text-yellow-500/80 border-yellow-500/20",
  ".usdz":  "bg-pink-500/10 text-pink-500/80 border-pink-500/20",
}

export const assets: Asset[] = [
  // SCENES
  {
    id: 1,
    name: "Brutalist Studio",
    slug: "brutalist-studio",
    category: "SCENE",
    formats: [".blend"],
    free: false,
    isNew: true,
    description: "Raw concrete interior. HDRI-ready. Zero lighting setup required.",
    meta: "2.4M polys · Cycles / EEVEE",
  },
  {
    id: 2,
    name: "Desert Canyon Vista",
    slug: "desert-canyon-vista",
    category: "SCENE",
    formats: [".blend"],
    free: false,
    isNew: false,
    description: "Photorealistic canyon exterior with volumetric atmosphere and distance haze.",
    meta: "1.1M polys · Cycles",
  },
  {
    id: 3,
    name: "Neon Alley Night",
    slug: "neon-alley-night",
    category: "SCENE",
    formats: [".blend"],
    free: false,
    isNew: false,
    description: "Urban night environment. Fully lit RGB neon setup. Rain-wet surfaces.",
    meta: "3.2M polys · Cycles / EEVEE",
  },
  {
    id: 4,
    name: "Void Stage Vol.1",
    slug: "void-stage-vol-1",
    category: "SCENE",
    formats: [".blend"],
    free: true,
    isNew: false,
    description: "Minimal product stage. Drop in any model, render immediately. No setup.",
    meta: "140K polys · Cycles / EEVEE",
  },

  // GOBOS
  {
    id: 5,
    name: "Venetian Shadows Vol.1",
    slug: "venetian-shadows-vol-1",
    category: "GOBO",
    formats: [".exr", ".png"],
    free: true,
    isNew: false,
    description: "12 venetian blind shadow patterns. Product and portrait applications.",
    meta: "4K · 12 textures",
  },
  {
    id: 6,
    name: "Forest Canopy Vol.1",
    slug: "forest-canopy-vol-1",
    category: "GOBO",
    formats: [".exr", ".png"],
    free: false,
    isNew: false,
    description: "24 organic leaf and branch light break patterns. Natural diffusion.",
    meta: "8K · 24 textures",
  },
  {
    id: 7,
    name: "Urban Grid Vol.2",
    slug: "urban-grid-vol-2",
    category: "GOBO",
    formats: [".exr", ".png"],
    free: false,
    isNew: true,
    description: "18 structural grid and architectural shadow patterns. Hard edge.",
    meta: "8K · 18 textures",
  },
  {
    id: 8,
    name: "Cinema Pack Vol.1",
    slug: "cinema-pack-vol-1",
    category: "GOBO",
    formats: [".exr", ".png"],
    free: false,
    isNew: false,
    description: "30 film-grade light cut patterns. Based on real cinema gobo shapes.",
    meta: "4K · 30 textures",
  },

  // 3D MODELS
  {
    id: 9,
    name: "Arch Chair Series",
    slug: "arch-chair-series",
    category: "MODEL",
    formats: [".blend", ".fbx", ".obj"],
    free: false,
    isNew: true,
    description: "4 chair variants. PBR materials. Unreal / Unity ready FBX included.",
    meta: "42K polys · PBR",
  },
  {
    id: 10,
    name: "Pendant Light Kit",
    slug: "pendant-light-kit",
    category: "MODEL",
    formats: [".blend", ".fbx"],
    free: false,
    isNew: false,
    description: "6 pendant styles. Emissive glass shader. Area light already configured.",
    meta: "18K polys · PBR",
  },
  {
    id: 11,
    name: "Brutalist Planter Set",
    slug: "brutalist-planter-set",
    category: "MODEL",
    formats: [".blend", ".fbx", ".obj"],
    free: false,
    isNew: false,
    description: "8 concrete planter variants. Procedural surface detail. No UV unwrap required.",
    meta: "12K polys · PBR",
  },
  {
    id: 12,
    name: "Hero Desk Setup",
    slug: "hero-desk-setup",
    category: "MODEL",
    formats: [".blend", ".fbx"],
    free: false,
    isNew: true,
    description: "Full hero-grade workstation. Display, peripherals, cables. Print-resolution textures.",
    meta: "280K polys · Cycles",
  },
  {
    id: 13,
    name: "Minimal Vase Set",
    slug: "minimal-vase-set",
    category: "MODEL",
    formats: [".blend", ".fbx", ".obj"],
    free: true,
    isNew: false,
    description: "3 ceramic vase forms. Subsurface scattering material included.",
    meta: "8K polys · PBR",
  },

  // MOCKUPS
  {
    id: 14,
    name: "Brand Box Vol.3",
    slug: "brand-box-vol-3",
    category: "MOCKUP",
    formats: [".blend"],
    free: false,
    isNew: true,
    description: "6 packaging angles. Smart UV for instant artwork replacement. No texture painting.",
    meta: "Cycles / EEVEE",
  },
  {
    id: 15,
    name: "Poster Frame Set",
    slug: "poster-frame-set",
    category: "MOCKUP",
    formats: [".blend"],
    free: false,
    isNew: false,
    description: "5 frame styles with texture displacement for material realism.",
    meta: "Cycles",
  },
  {
    id: 16,
    name: "Phone 16 Pro Rig",
    slug: "phone-16-pro-rig",
    category: "MOCKUP",
    formats: [".blend", ".fbx"],
    free: false,
    isNew: true,
    description: "Animated screen mockup. 60fps timeline. Reflection-accurate display shader.",
    meta: "Animated · Cycles / EEVEE",
  },
  {
    id: 17,
    name: "Apparel Flat Lay",
    slug: "apparel-flat-lay",
    category: "MOCKUP",
    formats: [".blend"],
    free: false,
    isNew: false,
    description: "T-shirt + hoodie flat lay. Baked cloth sim. Print-ready UV layout.",
    meta: "Cycles",
  },

  // ADD-ONS
  {
    id: 18,
    name: "Pure Bake",
    slug: "pure-bake",
    category: "ADDON",
    formats: [".py"],
    free: false,
    isNew: false,
    description: "Single-panel texture baking. Essential controls, zero interface clutter.",
    meta: "Blender 4.0+ · All platforms",
  },
  {
    id: 19,
    name: "StashOps",
    slug: "stashops",
    category: "ADDON",
    formats: [".py"],
    free: false,
    isNew: false,
    description: "Asset organization and batch import. Clears clutter, boosts pipeline speed.",
    meta: "Blender 4.0+ · All platforms",
  },
  {
    id: 20,
    name: "CineOps",
    slug: "cineops",
    category: "ADDON",
    formats: [".py"],
    free: false,
    isNew: false,
    description: "Cinematic camera control panel. Cuts, motion paths, lens presets in one panel.",
    meta: "Blender 4.0+ · All platforms",
  },
  {
    id: 21,
    name: "Scatter Pro",
    slug: "scatter-pro",
    category: "ADDON",
    formats: [".py"],
    free: false,
    isNew: true,
    description: "Intelligent object scattering with live density, scale, and rotation control.",
    meta: "Blender 4.0+ · All platforms",
  },

  // GEO NODES
  {
    id: 22,
    name: "Procedural City Block",
    slug: "procedural-city-block",
    category: "GEO NODE",
    formats: [".blend"],
    free: false,
    isNew: false,
    description: "Parameter-driven urban block generator. Adjustable density and facade variation.",
    meta: "Blender 4.0+",
  },
  {
    id: 23,
    name: "Vine & Growth System",
    slug: "vine-growth-system",
    category: "GEO NODE",
    formats: [".blend"],
    free: false,
    isNew: true,
    description: "Organic growth along any surface mesh. Animated growth timeline included.",
    meta: "Blender 4.0+",
  },
  {
    id: 24,
    name: "Particle Trail FX",
    slug: "particle-trail-fx",
    category: "GEO NODE",
    formats: [".blend"],
    free: true,
    isNew: false,
    description: "Motion trail node system. Velocity-based emission. Plug in, render.",
    meta: "Blender 4.0+",
  },

  // LATEST RELEASES
  {
    id: 25,
    name: "Pro Pure Bake",
    slug: "pro-pure-bake",
    category: "ADDON",
    formats: [".py"],
    free: false,
    isNew: true,
    description: "A simple Blender add-on for fast, clean texture baking with essential controls in one panel.",
    meta: "Blender 4.0+ · All platforms",
  },
  {
    id: 26,
    name: "Pro Daylight Studio Scene",
    slug: "pro-daylight-studio-scene",
    category: "SCENE",
    formats: [".blend"],
    free: false,
    isNew: true,
    description: "A clean studio scene with soft daylight shadows, cloud textures, and multiple gobo background options.",
    meta: "Cycles / EEVEE",
  },
  {
    id: 27,
    name: "Pro Sky Light Studio Scene",
    slug: "pro-sky-light-studio-scene",
    category: "SCENE",
    formats: [".blend"],
    free: false,
    isNew: true,
    description: "A minimalist display scene with a white pedestal and soft tree silhouettes.",
    meta: "Cycles / EEVEE",
  },
  {
    id: 28,
    name: "Standard Container 01",
    slug: "standard-container-01",
    category: "MODEL",
    formats: [".blend", ".fbx", ".obj"],
    free: false,
    isNew: true,
    description: "A 3D model of a standard shipping container with corrugated metal panels and double doors.",
    meta: "PBR · Game-ready",
  },
  {
    id: 29,
    name: "Standard CCTV Camera 01",
    slug: "standard-cctv-camera-01",
    category: "MODEL",
    formats: [".blend", ".fbx", ".obj"],
    free: false,
    isNew: true,
    description: "Premium 3D model of a surveillance camera. Perfect for renders, games, or animations.",
    meta: "PBR · Game-ready",
  },
  {
    id: 30,
    name: "Metallic Logo Mockup",
    slug: "metallic-logo-mockup",
    category: "MOCKUP",
    formats: [".blend"],
    free: false,
    isNew: true,
    description: "Elegant metallic logo mockup with customizable lighting and surface options.",
    meta: "Cycles / EEVEE",
  },
]
